plotting_info:
  path_chia_source: /home/toaster/workspace/chia-blockchain
  farmer_pubkey: ab179b1afdb7fef936b6b462f451a974c82c2fa8fca202d41aa946f7c6af80c257c12e382860bd4d6899e9c9efd6e92b
  pool_pubkey: b8f3748f3b46bf737d5cb5319eb584747b7d61ca9b24558452123a42b9d464af8e0ad2514701d274fb3fe2f6be5acdbe

  worker_info:
    - worker_name_prefix: nvme0n1
      path_tmp: /mnt/nvme0n1/chia/tmp
      path_fin_plots: /mnt/nvme0n1/chia/plots
      workers: 1
      time_between_starting_workers: 0
      threads_per_worker: 1
      ram_usage: 3400
      pin_to_core: False
    - worker_name_prefix: nvme1n1
      path_tmp: /mnt/nvme1n1/chia/tmp
      path_fin_plots: /mnt/nvme1n1/chia/plots
      workers: 7
      time_between_starting_workers: 3600
      threads_per_worker: 1
      ram_usage: 3400
      pin_to_core: False
    - worker_name_prefix: nvme2n1
      path_tmp: /mnt/nvme2n1/chia/tmp
      path_fin_plots: /mnt/nvme2n1/chia/plots
      workers: 7
      time_between_starting_workers: 3600
      threads_per_worker: 1
      ram_usage: 3400
      pin_to_core: False
    - worker_name_prefix: nvme3n1
      path_tmp: /mnt/nvme3n1/chia/tmp
      path_fin_plots: /mnt/nvme3n1/chia/plots
      workers: 7
      time_between_starting_workers: 3600
      threads_per_worker: 1
      ram_usage: 3400
      pin_to_core: False

buffers:
  - /mnt/sdb
  - /mnt/sdc
  - /mnt/sdd